# Generated by Django 6.0.1 on 2026-01-15 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('farms', '0001_initial'),
        ('market', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_registered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to='core.users')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farms')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farmers')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.plantingrecommendations')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='seasons.seasons')),
            ],
            options={
                'db_table': 'season_registrations',
                'managed': True,
                'indexes': [models.Index(fields=['status'], name='season_regi_status_0b9857_idx'), models.Index(fields=['recommendation'], name='season_regi_recomme_b7cde7_idx'), models.Index(fields=['farmer'], name='season_regi_farmer__82215b_idx')],
                'unique_together': {('recommendation', 'farmer', 'farm')},
            },
        ),
    ]
